// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Rasdah user's profile, roles, and company memberships.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = client(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }, { data: companies }] = await Promise.all([
      sb.from("profiles").select("user_id, email, full_name, branch_id").eq("user_id", userId).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", userId),
      sb.from("company_users").select("company_id, role, is_active").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile,
      roles: (roles ?? []).map((r) => r.role),
      companies: companies ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-branches.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_branches_default = defineTool2({
  name: "list_branches",
  title: "List branches",
  description: "List branches visible to the signed-in Rasdah user (RLS-scoped).",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50)."),
    company_id: z.string().uuid().optional().describe("Optionally filter by company id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, company_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client2(ctx).from("branches").select("id, name, company_id, region_id, is_active, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (company_id) q = q.eq("company_id", company_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { branches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-findings.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_findings_default = defineTool3({
  name: "list_findings",
  title: "List findings",
  description: "List non-conformities (findings) visible to the signed-in user, optionally filtered by status or branch.",
  inputSchema: {
    status: z2.enum(["open", "in_progress", "resolved", "closed"]).optional(),
    branch_id: z2.string().uuid().optional(),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, branch_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client3(ctx).from("non_conformities").select("id, status, score, branch_id, evaluation_id, assigned_to, due_date, resolved_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (branch_id) q = q.eq("branch_id", branch_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { findings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/recent-evaluations.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var recent_evaluations_default = defineTool4({
  name: "recent_evaluations",
  title: "Recent evaluations",
  description: "List the most recent submitted evaluations visible to the signed-in user.",
  inputSchema: {
    branch_id: z3.string().uuid().optional(),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ branch_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client4(ctx).from("evaluations").select("id, branch_id, assessor_id, status, overall_percentage, evaluation_date, created_at").eq("status", "submitted").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (branch_id) q = q.eq("branch_id", branch_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { evaluations: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jociyyeadabbwoqosvqc";
var mcp_default = defineMcp({
  name: "rasdah-mcp",
  title: "Rasdah MCP",
  version: "0.1.0",
  instructions: "Read-only tools for Rasdah, a quality-monitoring platform. All tools act as the signed-in user and respect the app's row-level security. Use `whoami` to check identity, `list_branches` for branches, `recent_evaluations` for latest submitted evaluations, and `list_findings` for non-conformities.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_branches_default, recent_evaluations_default, list_findings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
