ALTER TABLE public.template_priorities DROP CONSTRAINT IF EXISTS template_priorities_priority_level_check;
ALTER TABLE public.template_priorities ADD CONSTRAINT template_priorities_priority_level_check CHECK (priority_level IN ('critical','high','medium','low'));

ALTER TABLE public.template_criteria ADD COLUMN IF NOT EXISTS violation_value numeric;

DO $$
DECLARE
  v_template_id uuid := gen_random_uuid();
  v_domain_id uuid;
  v_freq_id uuid;
  v_prio_id uuid;
  v_cat_id uuid;
BEGIN
  UPDATE public.evaluation_templates SET is_active=false WHERE name='Food Establishment Compliance' AND company_id IS NULL;

  INSERT INTO public.evaluation_templates (id, name, name_ar, description, period_type, company_id, is_active, version)
  VALUES (v_template_id, 'Food Establishment Compliance', 'تقييم امتثال منشآت الأغذية والمطاعم', 'قالب رصدة لتقييم امتثال منشآت الأغذية والمطاعم - منظم حسب: المجال ← التكرار ← الأهمية ← الأسئلة', 'monthly', NULL, true, '1.0');

  v_domain_id := gen_random_uuid();
  INSERT INTO public.template_domains (id, template_id, name, name_ar, sort_order) VALUES (v_domain_id, v_template_id, 'الزي والنظافة الشخصية', 'الزي والنظافة الشخصية', 0);
  v_cat_id := gen_random_uuid();
  INSERT INTO public.template_categories (id, template_id, name, name_ar, weight, sort_order) VALUES (v_cat_id, v_template_id, 'الزي والنظافة الشخصية', 'الزي والنظافة الشخصية', 11.1111, 0);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'daily', 0);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 66.6667, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل العاملون ملتزمون بالزي الخاص بالعمل حسب الاشتراطات؟', 'هل العاملون ملتزمون بالزي الخاص بالعمل حسب الاشتراطات؟', 5, 16.6667, false, 0, 2000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل الزي نظيف وخالٍ من الاتساخات الظاهرة؟', 'هل الزي نظيف وخالٍ من الاتساخات الظاهرة؟', 5, 16.6667, false, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل جميع العاملين في إعداد وتحضير الغذاء يغطون شعر الرأس؟', 'هل جميع العاملين في إعداد وتحضير الغذاء يغطون شعر الرأس؟', 5, 16.6667, false, 2, 1000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل أظافر العاملين قصيرة ونظيفة؟', 'هل أظافر العاملين قصيرة ونظيفة؟', 5, 16.6667, false, 3, 1000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل لا توجد روائح شخصية غير مقبولة أو تدنٍ واضح في النظافة الشخصية للعاملين؟', 'هل لا توجد روائح شخصية غير مقبولة أو تدنٍ واضح في النظافة الشخصية للعاملين؟', 5, 16.6667, false, 4, 1000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يلتزم العاملون بغسل اليدين قبل التعامل مع الغذاء؟', 'هل يلتزم العاملون بغسل اليدين قبل التعامل مع الغذاء؟', 5, 16.6667, false, 5, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 33.3333, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يستخدم العاملون القفازات عند التعامل المباشر مع الغذاء الجاهز؟', 'هل يستخدم العاملون القفازات عند التعامل المباشر مع الغذاء الجاهز؟', 5, 33.3333, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يستخدم العاملون الكمامة عند الحاجة في مناطق التحضير؟', 'هل يستخدم العاملون الكمامة عند الحاجة في مناطق التحضير؟', 5, 33.3333, false, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يرتدون العاملون ساعات أو خواتم أو إكسسوارات أثناء إعداد الغذاء؟', 'هل يرتدون العاملون ساعات أو خواتم أو إكسسوارات أثناء إعداد الغذاء؟', 5, 33.3333, false, 2, NULL);

  v_domain_id := gen_random_uuid();
  INSERT INTO public.template_domains (id, template_id, name, name_ar, sort_order) VALUES (v_domain_id, v_template_id, 'شهادات العاملين الصحية', 'شهادات العاملين الصحية', 1);
  v_cat_id := gen_random_uuid();
  INSERT INTO public.template_categories (id, template_id, name, name_ar, weight, sort_order) VALUES (v_cat_id, v_template_id, 'شهادات العاملين الصحية', 'شهادات العاملين الصحية', 11.1111, 1);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'weekly', 0);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 100.0, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل جميع العاملين في إعداد أو تحضير أو تقديم الغذاء لديهم شهادات صحية؟', 'هل جميع العاملين في إعداد أو تحضير أو تقديم الغذاء لديهم شهادات صحية؟', 5, 25.0, true, 0, 1000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل جميع الشهادات الصحية سارية وغير منتهية؟', 'هل جميع الشهادات الصحية سارية وغير منتهية؟', 5, 25.0, true, 1, 1000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد أي عامل مباشر للعمل قبل إصدار الشهادة الصحية؟', 'هل يوجد أي عامل مباشر للعمل قبل إصدار الشهادة الصحية؟', 5, 25.0, true, 2, 1000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد إجراء يمنع العامل من مباشرة مهام الغذاء عند انتهاء شهادته؟', 'هل يوجد إجراء يمنع العامل من مباشرة مهام الغذاء عند انتهاء شهادته؟', 5, 25.0, true, 3, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'monthly', 1);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 66.6667, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل تم إصدار الشهادة الموحدة للعاملين في المدن التي تتطلب ذلك؟', 'هل تم إصدار الشهادة الموحدة للعاملين في المدن التي تتطلب ذلك؟', 5, 33.3333, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل اسم العامل في الشهادة مطابق لسجل الموظفين؟', 'هل اسم العامل في الشهادة مطابق لسجل الموظفين؟', 5, 33.3333, false, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل توجد قاعدة بيانات محدثة للشهادات الصحية لكل فرع؟', 'هل توجد قاعدة بيانات محدثة للشهادات الصحية لكل فرع؟', 5, 33.3333, false, 2, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 33.3333, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد تنبيه قبل انتهاء الشهادة الصحية بـ 30 يوم؟', 'هل يوجد تنبيه قبل انتهاء الشهادة الصحية بـ 30 يوم؟', 5, 100.0, false, 0, NULL);

  v_domain_id := gen_random_uuid();
  INSERT INTO public.template_domains (id, template_id, name, name_ar, sort_order) VALUES (v_domain_id, v_template_id, 'الترخيص والموقع والنشاط', 'الترخيص والموقع والنشاط', 2);
  v_cat_id := gen_random_uuid();
  INSERT INTO public.template_categories (id, template_id, name, name_ar, weight, sort_order) VALUES (v_cat_id, v_template_id, 'الترخيص والموقع والنشاط', 'الترخيص والموقع والنشاط', 11.1111, 2);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'monthly', 0);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 52.6316, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل المنشأة موجودة فعلياً في الموقع المسجل بالرخصة؟', 'هل المنشأة موجودة فعلياً في الموقع المسجل بالرخصة؟', 5, 33.3333, true, 0, 5000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل النشاط الفعلي داخل المنشأة مطابق للنشاط المرخص؟', 'هل النشاط الفعلي داخل المنشأة مطابق للنشاط المرخص؟', 5, 33.3333, true, 1, 4000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل توجد أعمال أو خدمات أو منتجات خارج نطاق الترخيص؟', 'هل توجد أعمال أو خدمات أو منتجات خارج نطاق الترخيص؟', 5, 33.3333, true, 2, 4000);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 31.5789, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم استخدام الرصيف أو الارتداد في أعمال المنشأة بدون تصريح؟', 'هل يتم استخدام الرصيف أو الارتداد في أعمال المنشأة بدون تصريح؟', 5, 50.0, false, 0, 4000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد تنبيه قبل انتهاء الرخصة؟', 'هل يوجد تنبيه قبل انتهاء الرخصة؟', 5, 50.0, false, 1, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 15.7895, 2);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل توجد وسائل دعابة ثابتة أو متحركة مقابل المحل أو حوله بدون ترخيص؟', 'هل توجد وسائل دعابة ثابتة أو متحركة مقابل المحل أو حوله بدون ترخيص؟', 5, 50.0, false, 0, 4000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل توجد نسخة محدثة من الرخصة متاحة للفرع أو في النظام؟', 'هل توجد نسخة محدثة من الرخصة متاحة للفرع أو في النظام؟', 5, 50.0, false, 1, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'quarterly', 1);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 62.5, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل عنوان الفرع الفعلي مطابق لعنوان الرخصة؟', 'هل عنوان الفرع الفعلي مطابق لعنوان الرخصة؟', 5, 50.0, true, 0, 5000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل جميع الوثائق المقدمة أو المحفوظة للرخصة صحيحة وسارية؟', 'هل جميع الوثائق المقدمة أو المحفوظة للرخصة صحيحة وسارية؟', 5, 50.0, true, 1, 5000);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 37.5, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل اسم المنشأة أو الفرع على اللوحة مطابق للرخصة؟', 'هل اسم المنشأة أو الفرع على اللوحة مطابق للرخصة؟', 5, 100.0, false, 0, NULL);

  v_domain_id := gen_random_uuid();
  INSERT INTO public.template_domains (id, template_id, name, name_ar, sort_order) VALUES (v_domain_id, v_template_id, 'الفصل بين الأقسام', 'الفصل بين الأقسام', 3);
  v_cat_id := gen_random_uuid();
  INSERT INTO public.template_categories (id, template_id, name, name_ar, weight, sort_order) VALUES (v_cat_id, v_template_id, 'الفصل بين الأقسام', 'الفصل بين الأقسام', 11.1111, 3);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'daily', 0);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 62.5, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم فصل المواد الخام عن الأغذية الجاهزة؟', 'هل يتم فصل المواد الخام عن الأغذية الجاهزة؟', 5, 50.0, true, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل أدوات ومواد التنظيف مخزنة بعيداً عن مناطق الغذاء؟', 'هل أدوات ومواد التنظيف مخزنة بعيداً عن مناطق الغذاء؟', 5, 50.0, true, 1, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 37.5, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل منطقة النفايات مفصولة عن مناطق الغذاء والتحضير؟', 'هل منطقة النفايات مفصولة عن مناطق الغذاء والتحضير؟', 5, 100.0, false, 0, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'weekly', 1);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 66.6667, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد فصل واضح بين الأقسام أو الأنشطة حسب الاشتراطات؟', 'هل يوجد فصل واضح بين الأقسام أو الأنشطة حسب الاشتراطات؟', 5, 50.0, false, 0, 1000);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل منطقة التحضير منفصلة عن منطقة التخزين؟', 'هل منطقة التحضير منفصلة عن منطقة التخزين؟', 5, 50.0, false, 1, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 33.3333, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل المساحات منظمة ولا يوجد تكدس يسبب تداخل العمليات؟', 'هل المساحات منظمة ولا يوجد تكدس يسبب تداخل العمليات؟', 5, 100.0, false, 0, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'monthly', 2);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 62.5, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تنفيذ نشاط إضافي غير مذكور في الترخيص داخل نفس الموقع؟', 'هل يتم تنفيذ نشاط إضافي غير مذكور في الترخيص داخل نفس الموقع؟', 5, 100.0, true, 0, 4000);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 37.5, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل تدفق العمل يمنع التداخل بين الاستلام والتحضير والتخزين والتقديم؟', 'هل تدفق العمل يمنع التداخل بين الاستلام والتحضير والتخزين والتقديم؟', 5, 100.0, false, 0, NULL);

  v_domain_id := gen_random_uuid();
  INSERT INTO public.template_domains (id, template_id, name, name_ar, sort_order) VALUES (v_domain_id, v_template_id, 'المكونات والمضافات الغذائية', 'المكونات والمضافات الغذائية', 4);
  v_cat_id := gen_random_uuid();
  INSERT INTO public.template_categories (id, template_id, name, name_ar, weight, sort_order) VALUES (v_cat_id, v_template_id, 'المكونات والمضافات الغذائية', 'المكونات والمضافات الغذائية', 11.1111, 4);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'daily', 0);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 62.5, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل تخلو المنشأة من مواد أو عبوات مجهولة المصدر أو بدون اسم واضح؟', 'هل تخلو المنشأة من مواد أو عبوات مجهولة المصدر أو بدون اسم واضح؟', 5, 50.0, true, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل جميع المكونات والمضافات غير منتهية الصلاحية؟', 'هل جميع المكونات والمضافات غير منتهية الصلاحية؟', 5, 50.0, true, 1, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 37.5, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل كميات المضافات المستخدمة في التحضير عند وجودها؟', 'هل يتم تسجيل كميات المضافات المستخدمة في التحضير عند وجودها؟', 5, 50.0, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل المضافات محفوظة حسب تعليمات التخزين؟', 'هل المضافات محفوظة حسب تعليمات التخزين؟', 5, 50.0, false, 1, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'monthly', 1);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 62.5, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل جميع المضافات الغذائية المستخدمة مسموحة ومطابقة للوائح؟', 'هل جميع المضافات الغذائية المستخدمة مسموحة ومطابقة للوائح؟', 5, 100.0, true, 0, 2000);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 37.5, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل مصدر كل مضاف غذائي معروف وموثق؟', 'هل مصدر كل مضاف غذائي معروف وموثق؟', 5, 50.0, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد إجراء يمنع شراء أو استخدام مكونات غير معتمدة؟', 'هل يوجد إجراء يمنع شراء أو استخدام مكونات غير معتمدة؟', 5, 50.0, false, 1, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'quarterly', 2);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 100.0, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل توجد قائمة محدثة بالمضافات المسموح استخدامها؟', 'هل توجد قائمة محدثة بالمضافات المسموح استخدامها؟', 5, 100.0, false, 0, NULL);

  v_domain_id := gen_random_uuid();
  INSERT INTO public.template_domains (id, template_id, name, name_ar, sort_order) VALUES (v_domain_id, v_template_id, 'التوصيل والنقل', 'التوصيل والنقل', 5);
  v_cat_id := gen_random_uuid();
  INSERT INTO public.template_categories (id, template_id, name, name_ar, weight, sort_order) VALUES (v_cat_id, v_template_id, 'التوصيل والنقل', 'التوصيل والنقل', 11.1111, 5);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'daily', 0);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 62.5, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم منع نقل الغذاء مع مواد تنظيف أو مواد غير غذائية؟', 'هل يتم منع نقل الغذاء مع مواد تنظيف أو مواد غير غذائية؟', 5, 100.0, true, 0, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 37.5, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل وسيلة التوصيل نظيفة ومناسبة لنقل الغذاء؟', 'هل وسيلة التوصيل نظيفة ومناسبة لنقل الغذاء؟', 5, 33.3333, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم استخدام حقيبة أو صندوق مناسب لحفظ الغذاء أثناء التوصيل؟', 'هل يتم استخدام حقيبة أو صندوق مناسب لحفظ الغذاء أثناء التوصيل؟', 5, 33.3333, false, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل توجد آلية للحفاظ على حرارة أو برودة المنتج أثناء النقل؟', 'هل توجد آلية للحفاظ على حرارة أو برودة المنتج أثناء النقل؟', 5, 33.3333, false, 2, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'monthly', 1);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 66.6667, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل وسيلة التوصيل التابعة للمنشأة مصرح لها؟', 'هل وسيلة التوصيل التابعة للمنشأة مصرح لها؟', 5, 100.0, false, 0, 3000);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 33.3333, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل بيانات المندوب أو السائق موثقة؟', 'هل بيانات المندوب أو السائق موثقة؟', 5, 33.3333, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم فحص وسائل التوصيل بشكل دوري؟', 'هل يتم فحص وسائل التوصيل بشكل دوري؟', 5, 33.3333, false, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل شكاوى العملاء المتعلقة بالتوصيل؟', 'هل يتم تسجيل شكاوى العملاء المتعلقة بالتوصيل؟', 5, 33.3333, false, 2, NULL);

  v_domain_id := gen_random_uuid();
  INSERT INTO public.template_domains (id, template_id, name, name_ar, sort_order) VALUES (v_domain_id, v_template_id, 'اللوحات والواجهة', 'اللوحات والواجهة', 6);
  v_cat_id := gen_random_uuid();
  INSERT INTO public.template_categories (id, template_id, name, name_ar, weight, sort_order) VALUES (v_cat_id, v_template_id, 'اللوحات والواجهة', 'اللوحات والواجهة', 11.1111, 6);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'weekly', 0);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'low', 100.0, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل الواجهة الخارجية نظيفة وخالية من التشوهات الواضحة؟', 'هل الواجهة الخارجية نظيفة وخالية من التشوهات الواضحة؟', 5, 100.0, false, 0, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'monthly', 1);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 66.6667, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل اللوحات أو الملصقات لا تعيق المداخل أو المخارج؟', 'هل اللوحات أو الملصقات لا تعيق المداخل أو المخارج؟', 5, 100.0, false, 0, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 33.3333, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل تخلو الواجهة من ملصقات غير مرخصة؟', 'هل تخلو الواجهة من ملصقات غير مرخصة؟', 5, 25.0, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل الملصقات الموجودة تقتصر على الدخول والخروج وأوقات العمل وطرق الدفع وQR؟', 'هل الملصقات الموجودة تقتصر على الدخول والخروج وأوقات العمل وطرق الدفع وQR؟', 5, 25.0, false, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل تم إزالة اللوحات أو الملصقات بعد انتهاء الترخيص؟', 'هل تم إزالة اللوحات أو الملصقات بعد انتهاء الترخيص؟', 5, 25.0, false, 2, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل تمت إعادة الواجهة أو الموقع لحالته الجيدة بعد إزالة اللوحة؟', 'هل تمت إعادة الواجهة أو الموقع لحالته الجيدة بعد إزالة اللوحة؟', 5, 25.0, false, 3, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'quarterly', 2);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 100.0, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل اللوحة الدعائية مطابقة للكود العمراني أو التصميم المعتمد للمنطقة؟', 'هل اللوحة الدعائية مطابقة للكود العمراني أو التصميم المعتمد للمنطقة؟', 5, 50.0, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد تصريح ساري للوحة الإعلانية عند الحاجة؟', 'هل يوجد تصريح ساري للوحة الإعلانية عند الحاجة؟', 5, 50.0, false, 1, NULL);

  v_domain_id := gen_random_uuid();
  INSERT INTO public.template_domains (id, template_id, name, name_ar, sort_order) VALUES (v_domain_id, v_template_id, 'تتبع الغذاء', 'تتبع الغذاء', 7);
  v_cat_id := gen_random_uuid();
  INSERT INTO public.template_categories (id, template_id, name, name_ar, weight, sort_order) VALUES (v_cat_id, v_template_id, 'تتبع الغذاء', 'تتبع الغذاء', 11.1111, 7);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'daily', 0);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 52.6316, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يمكن ربط المورد بالدفعة أو المادة المستلمة؟', 'هل يمكن ربط المورد بالدفعة أو المادة المستلمة؟', 5, 16.6667, true, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تدوين المواد الخام الداخلة في كل منتج؟', 'هل يتم تدوين المواد الخام الداخلة في كل منتج؟', 5, 16.6667, true, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تدوين المضافات المستخدمة ومصادرها؟', 'هل يتم تدوين المضافات المستخدمة ومصادرها؟', 5, 16.6667, true, 2, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يمكن تتبع المنتج النهائي إلى مكوناته الأصلية؟', 'هل يمكن تتبع المنتج النهائي إلى مكوناته الأصلية؟', 5, 16.6667, true, 3, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل تاريخ انتهاء الصلاحية موثق وواضح؟', 'هل تاريخ انتهاء الصلاحية موثق وواضح؟', 5, 16.6667, true, 4, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد رقم دفعة يمكن تتبعه للمنتجات التي تحتاج ذلك؟', 'هل يوجد رقم دفعة يمكن تتبعه للمنتجات التي تحتاج ذلك؟', 5, 16.6667, true, 5, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 31.5789, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل تاريخ استلام المنتجات أو المواد الخام؟', 'هل يتم تسجيل تاريخ استلام المنتجات أو المواد الخام؟', 5, 6.6667, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل نوع وطبيعة المنتجات أو المواد المستلمة؟', 'هل يتم تسجيل نوع وطبيعة المنتجات أو المواد المستلمة؟', 5, 6.6667, false, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل الكميات المستلمة؟', 'هل يتم تسجيل الكميات المستلمة؟', 5, 6.6667, false, 2, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل بيانات النقل للمواد المستلمة عند الحاجة؟', 'هل يتم تسجيل بيانات النقل للمواد المستلمة عند الحاجة؟', 5, 6.6667, false, 3, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم توثيق ظروف التخزين عند الاستلام للمواد الحساسة؟', 'هل يتم توثيق ظروف التخزين عند الاستلام للمواد الحساسة؟', 5, 6.6667, false, 4, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تدوين العمليات التي تتم على الغذاء داخل المنشأة؟', 'هل يتم تدوين العمليات التي تتم على الغذاء داخل المنشأة؟', 5, 6.6667, false, 5, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل أي تعديل أو إعادة معالجة للمنتج؟', 'هل يتم تسجيل أي تعديل أو إعادة معالجة للمنتج؟', 5, 6.6667, false, 6, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل تاريخ الإنتاج موثق للمنتجات المعدة أو المعبأة؟', 'هل تاريخ الإنتاج موثق للمنتجات المعدة أو المعبأة؟', 5, 6.6667, false, 7, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد سجل للجهات أو الفروع التي تم توزيع المنتج لها؟', 'هل يوجد سجل للجهات أو الفروع التي تم توزيع المنتج لها؟', 5, 6.6667, false, 8, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل اسم العميل أو الفرع المستلم؟', 'هل يتم تسجيل اسم العميل أو الفرع المستلم؟', 5, 6.6667, false, 9, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل عنوان الجهة المستلمة أو موقع الفرع؟', 'هل يتم تسجيل عنوان الجهة المستلمة أو موقع الفرع؟', 5, 6.6667, false, 10, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل تاريخ تسليم المنتجات؟', 'هل يتم تسجيل تاريخ تسليم المنتجات؟', 5, 6.6667, false, 11, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل نوع المنتجات المسلمة؟', 'هل يتم تسجيل نوع المنتجات المسلمة؟', 5, 6.6667, false, 12, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تسجيل الكميات المسلمة؟', 'هل يتم تسجيل الكميات المسلمة؟', 5, 6.6667, false, 13, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم توثيق بيانات النقل والتخزين أثناء التوزيع عند الحاجة؟', 'هل يتم توثيق بيانات النقل والتخزين أثناء التوزيع عند الحاجة؟', 5, 6.6667, false, 14, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 15.7895, 2);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يمكن معرفة من نفذ العملية ومتى؟', 'هل يمكن معرفة من نفذ العملية ومتى؟', 5, 100.0, false, 0, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'monthly', 1);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 52.6316, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد سجل محدث لجميع موردي الغذاء والمواد الخام؟', 'هل يوجد سجل محدث لجميع موردي الغذاء والمواد الخام؟', 5, 100.0, true, 0, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 31.5789, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يحتوي سجل الموردين على اسم المورد؟', 'هل يحتوي سجل الموردين على اسم المورد؟', 5, 14.2857, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يحتوي سجل الموردين على عنوان المورد؟', 'هل يحتوي سجل الموردين على عنوان المورد؟', 5, 14.2857, false, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تدوين مواد التعبئة والتغليف ومصادرها؟', 'هل يتم تدوين مواد التعبئة والتغليف ومصادرها؟', 5, 14.2857, false, 2, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل اسم المنتج الغذائي موثق؟', 'هل اسم المنتج الغذائي موثق؟', 5, 14.2857, false, 3, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يمكن استخراج بيانات المنتج بسرعة من السجلات؟', 'هل يمكن استخراج بيانات المنتج بسرعة من السجلات؟', 5, 14.2857, false, 4, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يمكن معرفة أماكن عرض أو بيع المنتج؟', 'هل يمكن معرفة أماكن عرض أو بيع المنتج؟', 5, 14.2857, false, 5, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل السجلات محفوظة بطريقة منظمة يسهل الوصول لها؟', 'هل السجلات محفوظة بطريقة منظمة يسهل الوصول لها؟', 5, 14.2857, false, 6, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 15.7895, 2);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل العلامة التجارية موثقة؟', 'هل العلامة التجارية موثقة؟', 5, 33.3333, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد رقم تعريفي أو باركود للمنتج عند توفره؟', 'هل يوجد رقم تعريفي أو باركود للمنتج عند توفره؟', 5, 33.3333, false, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل الحجم أو الوزن موثق للمنتج؟', 'هل الحجم أو الوزن موثق للمنتج؟', 5, 33.3333, false, 2, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'quarterly', 2);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'critical', 62.5, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يمكن تحديد المنتجات المتأثرة بسرعة عند وجود مشكلة؟', 'هل يمكن تحديد المنتجات المتأثرة بسرعة عند وجود مشكلة؟', 5, 33.3333, true, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم حفظ سجلات التتبع لمدة لا تقل عن 180 يوماً بعد انتهاء الصلاحية؟', 'هل يتم حفظ سجلات التتبع لمدة لا تقل عن 180 يوماً بعد انتهاء الصلاحية؟', 5, 33.3333, true, 1, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يمكن توفير سجلات التتبع عند الطلب؟', 'هل يمكن توفير سجلات التتبع عند الطلب؟', 5, 33.3333, true, 2, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 37.5, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يوجد شخص مسؤول عن نظام التتبع داخل المنشأة؟', 'هل يوجد شخص مسؤول عن نظام التتبع داخل المنشأة؟', 5, 100.0, false, 0, NULL);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'yearly', 3);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 66.6667, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل تتم مراجعة كفاءة نظام التتبع بشكل دوري؟', 'هل تتم مراجعة كفاءة نظام التتبع بشكل دوري؟', 5, 50.0, false, 0, NULL);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم تنفيذ اختبار تتبع داخلي للتأكد من إمكانية الوصول للمعلومات؟', 'هل يتم تنفيذ اختبار تتبع داخلي للتأكد من إمكانية الوصول للمعلومات؟', 5, 50.0, false, 1, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 33.3333, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم توثيق نتائج مراجعة التتبع والإجراءات الناتجة عنها؟', 'هل يتم توثيق نتائج مراجعة التتبع والإجراءات الناتجة عنها؟', 5, 100.0, false, 0, NULL);

  v_domain_id := gen_random_uuid();
  INSERT INTO public.template_domains (id, template_id, name, name_ar, sort_order) VALUES (v_domain_id, v_template_id, 'الإجراءات التصحيحية', 'الإجراءات التصحيحية', 8);
  v_cat_id := gen_random_uuid();
  INSERT INTO public.template_categories (id, template_id, name, name_ar, weight, sort_order) VALUES (v_cat_id, v_template_id, 'الإجراءات التصحيحية', 'الإجراءات التصحيحية', 11.1112, 8);
  v_freq_id := gen_random_uuid();
  INSERT INTO public.template_frequencies (id, domain_id, frequency_type, sort_order) VALUES (v_freq_id, v_domain_id, 'monthly', 0);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'high', 66.6667, 0);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل يتم رصد تكرار نفس نوع الملاحظة في نفس الفرع؟', 'هل يتم رصد تكرار نفس نوع الملاحظة في نفس الفرع؟', 5, 100.0, false, 0, NULL);
  v_prio_id := gen_random_uuid();
  INSERT INTO public.template_priorities (id, frequency_id, priority_level, weight, sort_order) VALUES (v_prio_id, v_freq_id, 'medium', 33.3333, 1);
  INSERT INTO public.template_criteria (category_id, priority_id, name, name_ar, max_score, weight, is_critical, sort_order, violation_value) VALUES (v_cat_id, v_prio_id, 'هل تظهر الفروع الأعلى في عدد أو خطورة الملاحظات؟', 'هل تظهر الفروع الأعلى في عدد أو خطورة الملاحظات؟', 5, 100.0, false, 0, NULL);

END $$;